name: Cora

metis_partition: true
shuffle_data: true
history_refresh: false
part_path: '/home/lihz/Codes/dgl/MyCodes/GNNAutoScale/PartitionedGraph'

self_loop: false
num_layers: 2
hidden_channels: 16
dropout: 0.5
num_parts: 40
batch_size: 10
inference_batch_size: null
lr: 0.01
reg_weight_decay: 5e-4
nonreg_weight_decay: 0.0
grad_norm: 1.0
epochs: 200
test_every: 1

drop_input: true
batch_norm: false
residual: false
linear: false
pool_size: null
buffer_size: null